### ISSUE TITLE
Cannot find module 'core-js/modules/es6.array.filter' (fixed by installing core-js)

### ISSUE THREAD

**Issue by pauleveritt** [goblindegook/gatsby-starter-typescript#3]
Just cloned this and gave it a shot. Running develop gave ``Error: Cannot find module 'core-js/modules/es6.array.filter'``

As explained in [this ticket](https://github.com/gatsbyjs/gatsby/issues/7862) a recent build, recent Babel releases have broken things, fixed by installing core-js as a peer dependency.

On a side note, any interest in contributors? I'm doing Gatsby+TS+testing and want to collaborate on best practices.

**Comment by goblindegook** [comment]
Hi @pauleveritt, and apologies, I seem to have missed this. Are you getting this error with NPM? I haven't seen it on my end, but I've only tried with Yarn and the existing lockfile keeps things sane.

I need to update packages anyway, so I will look into this and probably provide an NPM lockfile as well. I also have a few changes coming up soon, including support for MDX, but in the meantime feel free to suggest improvements if you are so inclined.

**Comment by pauleveritt** [comment]
Correct, I should have mentioned that it was npm. Sorry!

I'd be quite interested in MDX, quite soon, and am willing to help.

Also, [MS recently signaled intent to switch from TSLint to ESLint](https://github.com/Microsoft/TypeScript/issues/29288). Perhaps this starter could do the switch? If you'd like, I'll make a ticket.

**Comment by goblindegook** [comment]
Hi @pauleveritt, I already have MDX integrated on a (private) project, and will migrate those changes here by next weekend.

And yes, I also fully intend to migrate all my TypeScript projects (including this one) to ESLint once integration with language services is in place to support [semantic rules](https://palantir.github.io/tslint/usage/type-checking/). I recently read the TSLint team is shifting its focus to support ESLint instead, so I'm hoping there'll be a straightforward upgrade path for most projects.

**Comment by goblindegook** [comment]
Added `@babel/polyfill` (which wraps `core-js`) in 4871449137cbec99a662a6c3e0c178d4d0d21a02.

**Comment by goblindegook** [comment]
Can you confirm that this is working? New features will be coming separately.

**Comment by pauleveritt** [comment]
Sorry, late to the party. You are correct, it works.
