### ISSUE TITLE
Convert from TSLint to ESLint

### ISSUE THREAD

**Issue by pauleveritt** [goblindegook/gatsby-starter-typescript#5]
Here is [a branch](https://github.com/pauleveritt/gatsby-starter-typescript/tree/typescript-eslint) where I switched `gatsby-starter-typescript` from TSLint to ESLint, specifically typescript-eslint.

I removed what I believe are all traces of TSLint. I put in what seems to be a good .eslintrc.js for typescript-eslint. Since a bunch of files then complained (e.g. type -> interface), I made some changes and put in some comments to suppress warnings.

I tried to file a PR but got a permission denied.

**Comment by goblindegook** [comment]
There were some merge conflicts, ended up reapplying the changes by hand along with some other stuff. Thanks for this!
